derp:
  server:
    enabled: false
    region_id: 999
    region_code: "relay"
    region_name: "CKTech Relay"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_server_private.key
    automatically_add_embedded_derp_region: true
    ipv4: 192.168.1.1
    # ipv6: 2001:db8::1

  urls: []
  paths:
    - /etc/headscale/derp-map.yaml
  auto_update_enabled: true
  update_frequency: 24h
