  GNU nano 7.2                                                                                                                             derp-map.yaml                                                                                                                                      
Regions:
  - RegionID: 900
    RegionCode: "home"
    RegionName: "CKTech Home"
    Nodes:
      - Name: "home-relay"
        RegionID: 900
        HostName: "home.cktechx.io"
        IPv4: "68.238.54.36"
        DERPPort: 443
        STUNPort: 3478

  - RegionID: 901
    RegionCode: "cloud"
    RegionName: "CKTech Cloud"
    Nodes:
      - Name: "cloud-relay"
        RegionID: 901
        HostName: "relay.cktechx.io"
        IPv4: "198.96.95.69"
        DERPPort: 443
        STUNPort: 3478
