server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "COOKIE-SECRET-OPENSSL-BASE64-32"
  cookie_secure: true
  base_path: "/"

headscale:
  url: "http://localhost:8080"  # or https://ghost.cktechx.com if HTTPS + reverse proxy
  config_path: "/etc/headscale/config.yaml"
  config_strict: true
  headscale_api_key: "HEADSCALE-API-KEY"

oidc:
  issuer: "https://login.microsoftonline.com/tenantIDHERE/v2.0"
  client_id: "APP-REG-CLIENT-ID"
  client_secret: "CLIENT-SECRET-AZURE"
  headscale_api_key: "HS-API-HERE"
  token_endpoint_auth_method: "client_secret_post"
  disable_api_key_login: false
  redirect_uri: "https://hs.mydomain.com/admin/oidc/callback"
  extra_params:
    domain_hint: mydomain.com
  allowed_domains:
    - mydomain.com
