services:
  derper:
    image: fredliang/derper:latest
    container_name: hs-derp
    restart: unless-stopped
    network_mode: host
    environment:
      - DERP_DOMAIN=titan.cktechx.io
      - DERP_ADDR=:8443
      - DERP_REGION_NAME=CKTech Titan
      - DERP_STUN=true
      - DERP_ENABLE_LETSENCRYPT=false
